name       : python-sphinxcontrib-jsmath
version    : 1.0.1
release    : 2
source     :
    - https://github.com/sphinx-doc/sphinxcontrib-jsmath/archive/1.0.1.tar.gz : 1a20febedb885c78f2e2c29b6f4c1e4e6fe0ac4699378b624b805914491df064
license    : BSD-2-Clause
component  : programming.python
summary    : Sphinx extension for rendering math in HTML
description: |
    sphinxcontrib-jsmath is a sphinx extension which renders display math in HTML via JavaScript.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
